name: E2E Nightly

on:
  schedule:
    # Run every night at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [22]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npx nx build nx-gradle-plus

      - name: Run E2E Tests
        run: npx nx e2e nx-gradle-plus-e2e
        env:
          NODE_ENV: test

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-results-${{ matrix.os }}-node${{ matrix.node-version }}
          path: |
            dist/.nx/cache
            nx-gradle-plus-e2e/coverage
          retention-days: 7

  notify:
    runs-on: ubuntu-latest
    needs: e2e
    if: failure()
    steps:
      - name: Create Issue on Failure
        uses: actions/github-script@v7
        with:
          script: |
            const title = `E2E Nightly Tests Failed - ${new Date().toISOString().split('T')[0]}`;
            const body = `E2E nightly tests failed. Check the [workflow run](${context.payload.repository.html_url}/actions/runs/${context.runId}) for details.`;

            // Check if an issue already exists
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'e2e-failure',
              state: 'open'
            });

            if (issues.data.length === 0) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: body,
                labels: ['e2e-failure', 'bug']
              });
            }
